### ISSUE TITLE
[Bug] The script stopped working

### ISSUE THREAD

**Issue by Wexutar** [tajnymag/tinder-deblur#10]
When i was browsing my Tinder in the last 2 days, i encountered a new issue recently. The script only shows the  second person who liked me ,and the rest keep blurred, hidden. It is the same on chrome and firefox too.

**Comment by tajnymag** [comment]
I deleted my Tinder account, so I can't test it right away, but could you please try these steps and post the result?

1. temporarily disable tinder-deblur in your script manager extension
2. load the likes screen on Tinder
3. open the developer console by pressing
4. switch to the Console tab
5. paste this command `document.querySelectorAll('.Expand.enterAnimationContainer > div:nth-child(1)')`
6. post a screenshot of the output

The thing I'd like to check is, whether tinder-deblur is able to find all 10 elements in the page

**Comment by M9k** [comment]
It stopped working for me too, but for me it just keep swaps the penultimate image with other blur images. Really strange.
![image](https://user-images.githubusercontent.com/9288402/206548949-2b80499f-71a1-4aab-9573-673d01eb5517.png)

**Comment by tajnymag** [comment]
@M9k 

Hmm, that seems like we did find the correct elements, or at least their parent/child. Maybe the API response has changed? Could you try intercepting it using the tools in Network tab?

**Comment by mpanowicz** [comment]
The image returned from API for a few matches is blurred. e.g. https://images-ssl.gotinder.com/xyz/blurred_xyz.jpg

I've changed building the URL in line
https://github.com/tajnymag/tinder-deblur/blob/main/tinder.user.js#L30
to
`const teaserImage = "https://preview.gotinder.com/" + teaser.user._id + "/original_" + teaser.user.photos[0].id + ".jpeg";`

**Comment by tajnymag** [comment]
> The image returned from API for a few matches is blurred. e.g. https://images-ssl.gotinder.com/xyz/blurred_xyz.jpg
> 
> I've changed building the URL in line
> https://github.com/tajnymag/tinder-deblur/blob/main/tinder.user.js#L30
> to
> `const teaserImage = "https://preview.gotinder.com/" + teaser.user._id + "/original_" + teaser.user.photos[0].id + ".jpeg";`

Wait, that works? Wow, thank you. Do the unblurred images from preview.gotinder.com match the blurred images that are normally displayed?

If so, it's a major discovery and I'll implement it in the morning.

**Comment by mpanowicz** [comment]
I think so, it worked for me. I've built that URL based on one returned correctly (the second person).

**Comment by tajnymag** [comment]
Ok, expect an experimental update in the following 24 hours. Thank you very much.

**Comment by M9k** [comment]
> The image returned from API for a few matches is blurred. e.g. https://images-ssl.gotinder.com/xyz/blurred_xyz.jpg
> 
> I've changed building the URL in line https://github.com/tajnymag/tinder-deblur/blob/main/tinder.user.js#L30 to `const teaserImage = "https://preview.gotinder.com/" + teaser.user._id + "/original_" + teaser.user.photos[0].id + ".jpeg";`

It works flawless!

**Comment by tajnymag** [comment]
Pushed version 2.5. The userscript should update itself automatically when your userscript manager checks for updates, or you can force the refresh manually.

Let me know, if it works correctly, so I can close the issue :slightly_smiling_face:

**Comment by anatolek123456** [comment]
seems to be broken at least for me still, pre-update it only unblurred 1 pic, now it shows the blurred pics for like half a second upon page load and then every pic just goes black/white (depending on dark mode on/off)

**Comment by mpanowicz** [comment]
@tajnymag there is missing `:` after https in the URL `https//preview.gotinder.com`

**Comment by anatolek123456** [comment]
yep that fixed it

**Comment by tajnymag** [comment]
fok

**Comment by tajnymag** [comment]
Pushed v2.6 with fixed typo found by @mpanowicz

**Comment by JotaroLR** [comment]
Salut à tous ! Je n'arrive plus à déflouter les matchs sur tinder pouvez nous m'aider merci d'avance ?
