### ISSUE TITLE
[Bug] Not  Deblurring when photos are in images-ssl.gotinder.com

### ISSUE THREAD

**Issue by aamezua** [tajnymag/tinder-deblur#11]
The script only works with photos in preview.gotinder.com
Solved

**Comment by tajnymag** [comment]
@aamezua How did you solve the issue?

**Comment by aamezua** [comment]
When blurred photos server is images-ssl.gotinder.com, the 24 chars following the server name are the user id. 
Fetch the user's data from api.gotinder.com/user/{user_id}. The original unblurred photos are in user.photos[n].url

**Comment by tajnymag** [comment]
Don't close the issue, until it is resolved for others too.

**Comment by aamezua** [comment]
Oops!
