### ISSUE TITLE
[Bug] 2 profiles out of 6 not deblurred

### ISSUE THREAD

**Issue by KaKi87** [tajnymag/tinder-deblur#22]
Hello,

I currently have 6 profiles displayed in `/app/gold-home`.

Until v2.x, all of these got deblurred.

Since v3.0, the last two don't get deblurred.

Thanks

**Comment by tajnymag** [comment]
could you please try version v4.0b from this link and report, whether it's working correctly?
https://github.com/tajnymag/tinder-deblur/raw/368e1264da42c70621f1b3b7caf044206328a0d6/tinder.user.js

**Comment by KaKi87** [comment]
Wow, this looks too good to be true, it works insanely well, thanks !!!

**Comment by tajnymag** [comment]
Great. I'll close the issue once v4 is released then

**Comment by AntonStoeckl** [comment]
No change here for me, on Firefox with Greasemonkey.
From the 10 likes that are shown, 4 are not deblurred. Not even the latest 4 in the order they are shown, one is in the middle. I have deleted all Tinder cookies in between, removed the user script and re-installed it, no change.

Edit: Exactly the same on Chromium (I'm on Linux), except that I don't see the "X" and "Heart" buttons on Chromium, which I see on Firefox.

**Comment by AntonStoeckl** [comment]
No change here for me, on Firefox with Greasemonkey.
From the 10 likes that are shown, 4 are not deblurred. Not even the latest 4 in the order they are shown, one is in the middle. I have deleted all Tinder cookies in between, removed the user script and re-installed it, no change.

Edit: Exactly the same on Chromium with Tampermonkey.

**Comment by jgeramb** [comment]
Can you try this version @AntonStoeckl: https://gist.github.com/JustixDevelopment/ca3dd0861fd180622df39c156df6c400

**Comment by AntonStoeckl** [comment]
@JustixDevelopment No change with that one. konsole output looks ok, have not spotted anything suspicious in dev tools, same as with v4.0.b

I got a superlike yesterday which worked fine to deblur, except that it only loaded one pic, while the profile had many.
So it's not the most recent likes that don't deblur.
As Tinder is doing loads of tricks to fool people into buying subscriptions my impression is that those might be some sort of fake likes.

**Comment by jgeramb** [comment]
@AntonStoeckl Alles klar. Es werden alle Bilder geladen, wenn du mit der Maus über das Bild hoverst, heute mache ich noch eine komplette Profilansicht und eine Bilder-Auswahl, wie es auch im normalen Feed ist. Du könntest in den DevTools mal im Netzwerk-Tab auf die Rückgabe der „teasers“ Anfrage schauen, vielleicht findest du da mehr heraus. Ansonsten kannst du mir auch gerne über GitHub Gist die Ausgabe im JSON-Format schicken, dann überprüfe ich die Profile selbst mal und kann Fake-Profile automatisch ausblenden.

**Comment by AntonStoeckl** [comment]
Hm, ich finde keine teasers Anfrage, siehe Screenshot.

![Bildschirmfoto vom 2023-04-06 17-37-16](https://user-images.githubusercontent.com/776322/230428946-4522d0b5-d5bf-4e2a-b61e-9e532e9d660b.png)

**Comment by jgeramb** [comment]
Vielleicht etwas weiter unten? Benutze sonst mal das Suchfeld, aber warte ein paar Sekunden bis die grundlegenden Elemente vom Script geladen wurden (Ads weg, andere Navigation etc.).

**Comment by AntonStoeckl** [comment]
Das unterste sind schon nachgeladene Requests, bis zum Screenshot war da sicher schon eine Minute vergangen.
Ich bin mir relativ sicher, dass ich den request früher auch schon mal gesehen habe.
Vermutlich, als ich auch "echte" Likes hatte.
Ich kann mal schauen, wenn wieder ein Like reinkommt, der deblurred werden kann, ob der Request dann auftaucht.
Könnte aber dauern, mein Profile ist sehr dry, mich hat schon jeder in meinem Filter gesehen und umgekehrt.
Für mich sieht es immer mehr danach aus, also ob Tinder diese 4 "fake likes" per Script einblendet, um mich bei der Stange zu halten. :D
Hm, ich ändere mal meine Age Range nach oben, vielleicht werden ich den Omas dann auch angezeigt, bei den älteren Damen bin ich zumindest auf Bumble recht  beliebt.

**Comment by jojohnson-jsj** [comment]
I also have a few likes that refuse to unblur. I see one error in the console (in Firefox) but haven't figured out what the issue is. I disabled all of my extensions on the site and I'm still getting the same error.

![image](https://user-images.githubusercontent.com/55406785/230451298-94811d58-a1c0-4b39-a84d-4ef7ec700f43.png)

**Comment by jgeramb** [comment]
Alles klar, so sieht das ganze nun bei mir aus: https://streamable.com/411h57
Das ist die Version, die ich benutze: https://gist.github.com/JustixDevelopment/8870717f2530b36d1015e9ac497fed26

Ich hab das ganze gerade nochmal in Firefox getestet und hier scheint auch alles zu klappen:
![Screenshot (000181)](https://user-images.githubusercontent.com/30385979/230480734-d58f4036-6511-4605-9b26-469c45b0622b.png)

**Comment by AntonStoeckl** [comment]
Hm, bei mir eher noch kaputter, sieht wieder im Firefox und Chromium gleich aus. Ich bin auf Linux, probiere es nachher mal auf Windows.

Hier ist jetzt wieder ein nagelneuer "echter" Like dabei.
Eine Teasers anfrage sehe ich wieder nicht, der Screenshot ist wieder nach Daten im Browser löschen und über eine Minute warten.

![Bildschirmfoto vom 2023-04-07 14-12-36](https://user-images.githubusercontent.com/776322/230606905-fb988c0a-48c9-4202-ab5b-4b3b30c66444.png)

Chrome auf Windows sieht genauso aus, wie Chromium und Firefox auf Linux.
Da bei Dir das Problem nicht auftaucht, vermute ich um so mehr, dass Tinder hier nicht existierende Likes unterjubeln will.

**Comment by AntonStoeckl** [comment]
Debugged it. Added console.debug(`${teaserImage}`); in line 155 (before if (teaserImage.includes('images-ssl')) 

![Bildschirmfoto vom 2023-04-08 14-12-57](https://user-images.githubusercontent.com/776322/230720489-def55adf-f0dd-4652-8901-ff90dc51fe6f.png)

I guess this shows clearly that 4 of my 6 likes are fake, different URL without a userID. I just wonder how this would look like if I had gold? What would happen to the 4 fake likes?

**Comment by tajnymag** [comment]
@AntonStoeckl, hmm, interestingly shady. What would you expect the behavior of the userscript to be? Filtering those matches out?

**Comment by AntonStoeckl** [comment]
@tajnymag I personally would find it most useful if the script just marks them as "FAKE" in some way.

**Comment by jgeramb** [comment]
I just removed the "fake" profiles for now @AntonStoeckl.

**Comment by jgeramb** [comment]
@AntonStoeckl the latest development version marks the teasers as invalid now.

**Comment by nutchedd** [comment]
it's still working for you ?

**Comment by jgeramb** [comment]
> it's still working for you ?

yes the dev version works for me
