### ISSUE TITLE
[Bug] Refresh Error

### ISSUE THREAD

**Issue by NickyFINN** [tajnymag/tinder-deblur#24]
Cannot see over 8 likes on google chrome. When ever I scroll it throws an error and reverts back to blured/popup.

**Comment by tajnymag** [comment]
Could you please try the development version?

[https://raw.githubusercontent.com/tajnymag/tinder-deblur/develop/tinder.user.js](https://raw.githubusercontent.com/tajnymag/tinder-deblur/develop/tinder.user.js)

**Comment by NickyFINN** [comment]
perfect
