### ISSUE TITLE
Thumbs are black after v4

### ISSUE THREAD

**Issue by naoliv** [tajnymag/tinder-deblur#28]
It seems that after version 4 something went wrong:

![](https://github.com/tajnymag/tinder-deblur/assets/982338/113762a7-f01f-4c70-ba6f-2be839499245)

Sometimes I can properly see the thumbs, but they start to disappear after a while.

**Comment by imongithub123** [comment]
im also getting this

**Comment by tajnymag** [comment]
Probably related to https://github.com/tajnymag/tinder-deblur/issues/27

**Comment by naoliv** [comment]
Indeed it seems to be #27, thanks!
