### ISSUE TITLE
[Bug] Already patched?

### ISSUE THREAD

**Issue by 825i** [tajnymag/tinder-deblur#3]
Followed the instructions. Nothing seems to happen at all. With the old script they'd unblur after a small delay. Now nothing happens.

Tinder also sent me a notification in the top right saying "an update to the app has been released, please reload the page".

I'm assuming they have patched this already.

Using Chrome on MacOS: Version 102.0.5005.115 (Official Build) (arm64)
With Tampermonkey

[![Screenshot-2022-06-13-at-10-57-19.png](https://i.postimg.cc/m2MFrzLf/Screenshot-2022-06-13-at-10-57-19.png)](https://postimg.cc/TpdP7P5C)

**Comment by 825i** [comment]
Just tested with Violentmonkey

Version 2.13.0
Updated
May 4, 2021

for Chrome also. Same results. I think it's already patched.

**Comment by tajnymag** [comment]
It could also be caused by a known race condition (https://github.com/tajnymag/tinder-deblur/pull/1).

Could you check the console whether there is an error about an element not found?

**Comment by tajnymag** [comment]
Update:
I've released version 2.2 with a bit improved page load awaiting and logging to console each time the deblur function is called. Please check the function was actually called. The race condition is still there and I'm still fighting to fix it for good. After moving from loop based unblurring to observation unblurring, the page detection is a bit flakey.

For other readers:
Try to refresh the Tinder app with CTRL+SHIFT+R.

**Comment by 0tr3bor** [comment]
Version 2.2 with violentmonkey doesn't work in my pc with Chrome or Firefox.
I am using version 1.4 console, which discovers the likes, but it does not show the last results, but always the same ones.

**Comment by tajnymag** [comment]
> Version 2.2 with violentmonkey doesn't work in my pc with Chrome or Firefox. I am using version 1.4 console, which discovers the likes, but it does not show the last results, but always the same ones.

Try to refresh the app and check the console.

For the static likes, there's nothing I can do (https://github.com/tajnymag/tinder-deblur/issues/2#issuecomment-1153676936)

**Comment by tajnymag** [comment]
I've pushed version 2.3 which includes the old loop based behavior as a fallback. That should fix all the issued with the deblurring not being called.
