### ISSUE TITLE
Loading screen on indefinitely 

### ISSUE THREAD

**Issue by imongithub123** [tajnymag/tinder-deblur#32]
<img width="1121" alt="Screen Shot 2023-05-18 at 6 06 38 PM" src="https://github.com/tajnymag/tinder-deblur/assets/110348663/cf60cc79-dcbc-437c-ab38-c3cf16fe93c0">

**Comment by tajnymag** [comment]
Probably related to: https://github.com/tajnymag/tinder-deblur/issues/27
