### ISSUE TITLE
Getting Error 403 when unblur images

### ISSUE THREAD

**Issue by sebastianjavier08** [tajnymag/tinder-deblur#38]
Browser console shows repetitive errors when trying to unblur profile pictures:
GET https://api.gotinder.com/user/5e31e23b59af9101007192f2 403
Could not load user '5e31e23b59af9101007192f2'

Version tested
- Tinder-deblur 4.1
- Tinder 4.19.0

**Comment by jgeramb** [comment]
Tinder recently changed their user API endpoint, try this version for now: https://github.com/JustixDevelopment/tinder-deblur/raw/develop/tinder.user.js
