### ISSUE TITLE
[FAQ] Really more of just a question.

### ISSUE THREAD

**Issue by DaOrangeee** [tajnymag/tinder-deblur#46]
Let's say I may of accidently clicked X on all my likes, is there a way for them to reappear? Is it over time or are they gone forever?

**Comment by tajnymag** [comment]
By clicking X, I believe you passed them. However, if you deleted you localstorage for tinder.com, they might reappear.

https://www.howtogeek.com/664912/how-to-clear-storage-and-site-data-for-a-single-site-on-google-chrome/

**Comment by DaOrangeee** [comment]
yes thank you that worked!
