### ISSUE TITLE
Version 5 no longer work

### ISSUE THREAD

**Issue by mtt0909** [tajnymag/tinder-deblur#50]
Sometimes I need to click a few times before the profiles are listed. 
When I click the green heart to match, nothing happens.
If I retry the matches continue to show up in the list, (although I may need to click a few times  again - see line 1) but each time the like fails to match

**Comment by mnkhbldd** [comment]
same here

**Comment by tajnymag** [comment]
https://github.com/tajnymag/tinder-deblur/issues/45

**Comment by mtt0909** [comment]
So far as I checked I don't think what I reported is the same issue as #45 
The profiles all loaded correctly but the green heart wasn't producing a match against legitimate likes. 
It seems to have been a temporary glitch though and it's now been working again the past week.
