### ISSUE TITLE
No likes available problem

### ISSUE THREAD

**Issue by mmu56** [tajnymag/tinder-deblur#51]
![Screenshot 2023-07-02 095822](https://github.com/tajnymag/tinder-deblur/assets/138356508/77ff4bbe-1bf9-4288-bfea-900c8b35ed87)
without script
![Screenshot 2023-07-02 095931](https://github.com/tajnymag/tinder-deblur/assets/138356508/5a33a979-05bb-4ec0-8fdd-d859e6ad710b)
with script

**Comment by tajnymag** [comment]
See issue: https://github.com/tajnymag/tinder-deblur/issues/44
