### ISSUE TITLE
[Bug] Doesnt seem to be working anymore 

### ISSUE THREAD

**Issue by DarkForest6** [tajnymag/tinder-deblur#6]
Worked fine before, as of 10/18 it does not seem to be unblurring anymore alongside Tinder's new update.

**Comment by jnss95** [comment]
I just took a look at the data the API provides and it looks like it now only provides pre blured images. So I guess they fixed it for good.

**Comment by tajnymag** [comment]
If what @Xeranor said is true, there's nothing really that can be done. I'm sorry, guys, but that's basically it.

**Comment by senpai1109** [comment]
script no work

**Comment by CallMeKuba** [comment]
> If what @Xeranor said is true, there's nothing really that can be done. I'm sorry, guys, but that's basically it.

![spidey](https://user-images.githubusercontent.com/81710224/197943767-7140e3c8-e1da-4dd8-921f-20e0b9323165.jpeg)

**Comment by Splicho** [comment]
Doesn't work anymore :(

**Comment by ArmasF31** [comment]
Well this did happen before a few weeks ago, but it came back so we might be lucky once again.

**Comment by Wexutar** [comment]
It doesn't work anymore for me either

**Comment by Jimbii238** [comment]
Can you write this script in JS ? 

https://www.reddit.com/r/hacking/comments/xxakn0/bypassing_tinders_security_fix_with_a_very_simple/

Apparently Tinder is still to incompetent.

Many thanks in advance if you gonna do it.

**Comment by tajnymag** [comment]
> Can you write this script in JS ? 
> 
> https://www.reddit.com/r/hacking/comments/xxakn0/bypassing_tinders_security_fix_with_a_very_simple/
> 
> Apparently Tinder is still to incompetent.
> 
> Many thanks in advance if you gonna do it.

Now that looks interesting. I don't have a Tinder account anymore, but I'll try to add it in and you can test it.

**Comment by DARKBOW923** [comment]
Rest in peace uwu

**Comment by tajnymag** [comment]
Pushed v2.4 with the header that [/u/nachfarbensortiert](https://www.reddit.com/user/nachfarbensortiert) uses in his unblurring script. No Tinder account -> can't test myself.

**Comment by DARKBOW923** [comment]
> Pushed v2.4 with the header that [/u/nachfarbensortiert](https://www.reddit.com/user/nachfarbensortiert) uses in his unblurring script. No Tinder account -> can't test myself.

wdym? did you made a push to the script or smth? the process to use it is the same as the first one you made?

**Comment by Jimbii238** [comment]
> 

Just tested, works perfectley fine for me with tampermonkey, thank you very much ! Have a nice week

**Comment by DARKBOW923** [comment]
> > 
> 
> Just tested, works perfectley fine for me with tampermonkey, thank you very much ! Have a nice week

Can confirm, but for some reason yesterday wasn't working with tampermonkey.

To make it work click the install link on this repo after installing tampermonker, reload the page and you will see the image unblurred.

**Comment by tajnymag** [comment]
> > Pushed v2.4 with the header that [/u/nachfarbensortiert](https://www.reddit.com/user/nachfarbensortiert) uses in his unblurring script. No Tinder account -> can't test myself.
> 
> wdym? did you made a push to the script or smth? the process to use it is the same as the first one you made?

Yes. And the script should update automatically once your userscript manager pulls for updates.

**Comment by tajnymag** [comment]
Seems fixed. Either re-open the issue or create a new one when tinder breaks the script again.
