### ISSUE TITLE
[Feature] Is it possible to get the profile link?

### ISSUE THREAD

**Issue by m7amad-nem** [tajnymag/tinder-deblur#8]
Since it gets the image it must know which user it belongs to, so it there should be some info on the user like profile link or userid for example.

**Comment by tajnymag** [comment]
Sorry, there isn't. Look at the response the server gives us. It's purposefully vague and limited.

**Comment by tajnymag** [comment]
If you find a way to construct the necessary requests from the data provided by the /teasers endpoint, I can incorporate it into the tool.

**Comment by m7amad-nem** [comment]
I only know a little about scripts and programming but I'll try to find something
