### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BravM** [tajnymag/tinder-deblur#9]
Works great! Thank you. Tinder only shows 10 people though, even if more than 10 people have liked you. I want to be able to see the people who have recently liked me,  and I spent a few hours looking through the scripts but I can't figure out how to increase the number of accounts you are able to view. You seem to know the Tinder API very well. Any ideas?

**Comment by tajnymag** [comment]
Duplicate of https://github.com/tajnymag/tinder-deblur/issues/2
